### ISSUE TITLE
the example seems to be broken. 

### ISSUE THREAD

**Issue by jkolobok** [upwork/golang-upwork#12]
I checked out the code. 
replaced consumer key/secret with my values, got access token/secret
the it panics on     _, jsonDataFromHttp := auth.New(client).GetUserInfo()

```
API server listening at: [::]:62002
debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-1001.0.13.3
 for x86_64.
Got a connection, launched process /private/var/folders/92/54vm31nx447_0rnyj0882yv40000gn/T/___1go_build_golang_upwork_example (pid = 37677).
panic: runtime error: slice bounds out of range [:1] with length 0

goroutine 1 [running]:
github.com/upwork/golang-upwork/api.(*ApiClient).Get(0xc00011fd80, 0x13c8c40, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/jkolobok/go/src/github.com/upwork/golang-upwork/api/client.go:131 +0x7c7
github.com/upwork/golang-upwork/api/routers/auth.a.GetUserInfo(0xc00017e000, 0xc000122d80, 0x0, 0xc000122db0, 0x13c696d, 0x3, 0x0, 0x0, 0x0, 0x0)
        /Users/jkolobok/go/src/github.com/upwork/golang-upwork/api/routers/auth/auth.go:41 +0x9b
main.main()
        /Users/jkolobok/go/src/golang-upwork/example/myapp.go:67 +0x13f
Exiting.

Debugger finished with exit code 0

```

**Comment by mnovozhylov** [comment]
hi @jkolobok ,

thank you for the report. The issue has been already fixed in the latest version (v1.3.5). Please, update and try once again.
